### ISSUE TITLE
Remove deprecated providers: `flux_install` and `flux_sync`

### ISSUE THREAD

**Issue by swade1987** [fluxcd/terraform-provider-flux#615]
This issue will track the work required to remove all code not related to the `flux_bootstrap_git` resource.

**Changes required to internal directory**

- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/data_install.go
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/data_install_test.go
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/data_sync.go
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/internal/provider/data_sync_test.go

**Changes required to the docs directory:**
- [x] Update docs to only include the `flux_bootstrap_git ` resource
- [x] Add an `index.md` to provide an overview on https://registry.terraform.io/providers/fluxcd/flux/1.2.3

**Changes required to the examples directory:**
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/customize-flux
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/data-sources
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/github
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/gitlab
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/gke_github
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/install-resource
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/install
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/multi-env
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/provider
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/resources/flux_bootstrap_git

**We should update the examples to include just the following scenarios:** 
- [x] Github bootstrap with SSH (no GPG)
- [x] Github bootstrap with SSH (with GPG)
- [x] Github bootstrap with SSH (customising the bootstrap options)
- [x] Gitlab bootstrap with SSH (no GPG)
- [x] Gitlab bootstrap with SSH (with GPG)
- [x] Helm install

**Changes required to the templates directory:**
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/templates/guides/breaking-provider-configuration.md.tmpl
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/templates/guides/extra-syncs.md.tmpl
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/templates/guides/install-helm-release.md.tmpl
- [x] Remove https://github.com/fluxcd/terraform-provider-flux/blob/main/templates/guides/migrating-to-resource.md.tmpl
- [x] Update the guides in the templates directory to match the examples in the section above.

**Comment by stefanprodan** [comment]
The removal of deprecated providers is scheduled for Flux v2.3 in April.
