### ISSUE TITLE
Preparation for v1.3.0 release

### ISSUE THREAD

**Issue by swade1987** [fluxcd/terraform-provider-flux#672]
### Description

This issue holds the necessary set of changes required for the upcoming v1.3.0 release.

- [x] PR that upgrades Flux to v2.3.0 
- [x] PR that upgrades k8s to 1.30
- [x] PR for [registry creds](https://github.com/fluxcd/terraform-provider-flux/issues/635)
- [x] PR for actual v1.3.0 release with changelog

### Would you like to implement a fix?

Yes

**Comment by swade1987** [comment]
Closing as release has now been cut.
